# Generated by Django 5.0.4 on 2024-06-18 19:53

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('descriptions', models.TextField(verbose_name='descriptions')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
            ],
            options={
                'db_table': 'Tarife',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('banned', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tarife_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.tarife')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('dc403d37-0833-4fcc-894f-c0cbe0105db6'), verbose_name='uuid')),
                ('parametrs', models.JSONField(verbose_name='parametrs')),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 18, 22, 53, 46, 978993))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.users')),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('descriptions', models.TextField(verbose_name='descriptions')),
                ('time_added', models.DateTimeField(default=datetime.datetime(2024, 6, 18, 22, 53, 46, 978993))),
                ('time_finish', models.DateTimeField(default=datetime.datetime(2024, 6, 18, 22, 53, 46, 978993))),
                ('status', models.CharField(max_length=55)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('appointed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointed_tasks', to='API.users', verbose_name='appointed')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executor_tasks', to='API.users', verbose_name='executor')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='CommentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2024, 6, 18, 22, 53, 46, 979741))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.task')),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.users')),
            ],
            options={
                'db_table': 'CommentTask',
            },
        ),
    ]
