# Generated by Django 5.0.4 on 2024-06-21 19:28

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 28, 52, 451860)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 28, 52, 451573)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 28, 52, 451579)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 28, 52, 451428)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9926c562-fccc-43ee-bec9-660635b2f49a'), verbose_name='uuid'),
        ),
    ]
