# Generated by Django 5.0.4 on 2024-06-21 19:36

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_commenttask_created_alter_task_time_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 36, 34, 742920)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 36, 34, 742649)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_finish',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 36, 34, 742656)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 19, 36, 34, 742506)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4d5c121c-e019-4fbb-8d52-1dd79ff383fe'), verbose_name='uuid'),
        ),
    ]
